Cell:
      Tcell: {}
      Bcell: {}
      NK: {}
      Dendritic: {}
      Mast: {}
      Neutrophil: {}
      Macrophage: {}
      Monocyte: {}
      Epithelial: {}
      Endothelial: {}
      Fibroblast: {}
      SmoothMuscle: {}
      Tumor: {}